name: Mosaic CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout project in $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
      
    # Install NodeJS
    - name: Install NodeJS
      uses: actions/setup-node@v1.1.0

    # Install project dependencies
    - name: Install Dependencies
      run: npm install
    
    # Run tests in CI mode
    - name: Unit Tests
      run: npm run test
      env:
        CI: true
