name: Mosaic CI - Test

on:
  pull_request:
    branches:
      - master

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: lts/hydrogen

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      env:
        cache-name: mosaic-dependencies
      with:
        path: node_modules
        key: mosaic-dependencies-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: npm ci

    - name: Generate Docs
      id: generate-docs
      run: |
        npm run build:storybook

    - name: Test runner
      run: |
        npx playwright install --with-deps
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server docs/latest --port 6006 --silent" \
          "npx wait-on tcp:127.0.0.1:6006 && npm run test:ci"
